services:
  authorisation-server:
    image: quay.io/keycloak/keycloak
    command: ["start-dev", "--import-realm"]
    container_name: keycloak
    ports:
      - 9090:8080
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    volumes:
      - ./authorisation-server:/opt/keycloak/data/import