spring:
    datasource:
        # Needs to be set explicitly to use database name testdb otherwise random guid is used
        # DB_CLOSE_DELAY prevents database from being destroyed after disconnect of schema creation
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    jpa:
        # Required for src/main/resources/data.sql to run after Hibernate schema creation
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
    jackson:
        # Global setting to not return null objects in JSON responses
        default-property-inclusion: NON_NULL
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9090/realms/demo

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
    info.env.enabled: true

info:
    app:
        name: @project.name@
        description: @project.description@
        version: @project.version@
        developer:
            name: @project.developers[0].name@
            email: @project.developers[0].email@
        license:
            name: @project.licenses[0].name@
            url: @project.licenses[0].url@

springdoc:
    swagger-ui:
        oauth:
            client-id: swagger-ui
            use-pkce-with-authorization-code-grant: true
